[package]
name = "tity3"
version = "0.1.0"
authors = ["Cote Céleste <celeste@cote21.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
libc = "*"
rand = "*"
